[build]
  command = "npm run build"
  publish = ""

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Functions configuration disabled for troubleshooting
# [functions]
#   node_bundler = "esbuild"
#   included_files = ["lib/**", "app/api/**"]

# API routes redirects disabled for troubleshooting
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/*"
#   status = 200

# Health check endpoint disabled
# [[redirects]]
#   from = "/health"
#   to = "/.netlify/functions/health"
#   status = 200

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Environment variables (will be set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin configuration for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"